Script started on Fri 20 Nov 2015 11:49:59 PM PST
[cbent002@hammer rshell]$ make
make rshell
make[1]: Entering directory `/home/csmajs/cbent002/CS100/rshell'
mkdir -p bin; \
	g++ -Wall -Werror -ansi -pedantic src/rshell.cpp src/Connector.cpp src/Semicolon.cpp src/DoubleAnd.cpp src/DoubleOr.cpp src/Arguments.cpp src/Executable.cpp src/Command.cpp src/Test.cpp src/ParsedCommand.cpp -o rshell; \
	mv rshell ./bin
make[1]: Leaving directory `/home/csmajs/cbent002/CS100/rshell'
[cbent002@hammer rshell]$ bin/rshell
Entering rshell.

[cbent002@hammer.cs.ucr.edu]€ echo A && echo B || echo C && echo D
A
B
D
[cbent002@hammer.cs.ucr.edu]€ (echo A && echo B) || (echo C && echo D)
A
B
[cbent002@hammer.cs.ucr.edu]€ echo A && (echo B || echo C) && echo D
A
B
D
[cbent002@hammer.cs.ucr.edu]€ ((echo A && echo B) || echooC) && echo D
A
B
D
[cbent002@hammer.cs.ucr.edu]€ (test src && echo OK) || (echo C && echo D)
OK
[cbent002@hammer.cs.ucr.edu]€ (test -f src && echo OK)H|| (echo C && echo D)
C
D
[cbent002@hammer.cs.ucr.edu]€ ([ src ] && echooOK) || (echo C && echooD)
OK
[cbent002@hammer.cs.ucr.edu]€ ([ssrc ] || echooOK) && (echooC || echooD)
[cbent002@hammer.cs.ucr.edu]€ ([ -f src ] || echo OK) && (echo C && echo D)
OK
C
D
[cbent002@hammer.cs.ucr.edu]€ ([ src ] || echo A) || (echo C || echo D)
C
[cbent002@hammer.cs.ucr.edu]€ (([ src ]&&&eecho[A) || echo B) && echo D
A
D
[cbent002@hammer.cs.ucr.edu]€ echo A && (([--f src ] && echo B) || echo D)
A
D
[cbent002@hammer.cs.ucr.edu]€ exit
Exiting rshell.

[cbent002@hammer rshell]$ exit

Script done on Fri 20 Nov 2015 11:54:00 PM PST
