Script started on Fri 20 Nov 2015 03:38:27 PM PST
]0;cbent002@hammer:~/CS100/rshell[?1034h[cbent002@hammer rshell]$ make
make rshell
make[1]: Entering directory `/home/csmajs/cbent002/CS100/rshell'
mkdir -p bin; \
	g++ -Wall -Werror -ansi -pedantic src/rshell.cpp src/Connector.cpp src/Semicolon.cpp src/DoubleAnd.cpp src/DoubleOr.cpp src/Arguments.cpp src/Executable.cpp src/Command.cpp src/Test.cpp src/ParsedCommand.cpp -o rshell; \
	mv rshell ./bin
make[1]: Leaving directory `/home/csmajs/cbent002/CS100/rshell'
]0;cbent002@hammer:~/CS100/rshell[cbent002@hammer rshell]$ bin/rshell 
Entering rshell.

[cbent002@hammer.cs.ucr.edu]€ test src && echo OK
OK
[cbent002@hammer.cs.ucr.edu]€ test -e src && echo OK
OK
[cbent002@hammer.cs.ucr.edu]€ test -f src && echo OK
[cbent002@hammer.cs.ucr.edu]€ test -f src || echo OK
OK
[cbent002@hammer.cs.ucr.edu]€ [ src ] && ech oOK    o OK
OK
[cbent002@hammer.cs.ucr.edu]€ [src ]&  && echoOK   OK
OK
[cbent002@hammer.cs.ucr.edu]€ [ src] && ech oOK    o OK
OK
[cbent002@hammer.cs.ucr.edu]€ [ -d src ] && ech  o OK
OK
[cbent002@hammer.cs.ucr.edu]€ [ -d src ] || ech oO   o OK
[cbent002@hammer.cs.ucr.edu]€ [ -f src ] && echo OK
[cbent002@hammer.cs.ucr.edu]€ | [ -  f src @ ] || echo OK
OK
[cbent002@hammer.cs.ucr.edu]€ [ ] && echo OK
[cbent002@hammer.cs.ucr.edu]€ test && ech oO   o OK
[cbent002@hammer.cs.ucr.edu]€ echoa    A && [ src ] && echo B
A
B
[cbent002@hammer.cs.ucr.edu]€ echo A && [ src ] || echo B
A
[cbent002@hammer.cs.ucr.edu]€ echo A && [ sfufdfsduh ] || echo B
A
B
[cbent002@hammer.cs.ucr.edu]€ test src&&echo OK
OK
[cbent002@hammer.cs.ucr.edu]€ [ src]&&ecj ho OK
OK
[cbent002@hammer.cs.ucr.edu]€ (test src && echo A) || echo B
A
[cbent002@hammer.cs.ucr.edu]€ (test src || echo B) && echo A
A
[cbent002@hammer.cs.ucr.edu]€ (te  (test src && echo A) || echo B) && ehco C     cho C
A
C
[cbent002@hammer.cs.ucr.edu]€ (([src     s  sr  c ] && echo A  ) || echo B) && echo C) 
A
C
[cbent002@hammer.cs.ucr.edu]€ (test src && echo A) || (echo B && echo C)
A
[cbent002@hammer.cs.ucr.edu]€ exit
Exiting rshell.

]0;cbent002@hammer:~/CS100/rshell[cbent002@hammer rshell]$ exit

Script done on Fri 20 Nov 2015 03:43:26 PM PST
